final List<String> pakistaniCities = [
  'Abbas Kili',
  'Chuhar Jamali',
  'Kamal Halq',
  'Karez',
  'Balgattar',
  'Timargara',
  'Rawala Kot',
  'Pir Jo Goth',
  'Khairpur Mir’s',
  'Islamabad',
  'Adilpur',
  'Ziarat',
  'Zhob',
  'Zaida',
  'Zahir Pir',
  'Zafarwal',
  'Yazman',
  'Wazirabad',
  'Chak Five Hundred Seventy-five',
  'Warah',
  'Wana',
  'Wah',
  'Vihari',
  'Utmanzai',
  'Uthal',
  'Usta Muhammad',
  'Umarkot',
  'Ubauro',
  'Turbat',
  'Topi',
  'Toba Tek Singh',
  'Thul',
  'Thatta',
  'Tharu Shah',
  'Taunsa',
  'Tank',
  'Tangwani',
  'Tangi',
  'Tando Muhammad Khan',
  'Tando Mitha Khan',
  'Tando Jam',
  'Tando Bago',
  'Tando Allahyar',
  'Tando Adam',
  'Tandlianwala',
  'Talhar',
  'Talamba',
  'Talagang',
  'Thal',
  'Swabi',
  'Surab',
  'Sukkur',
  'Sukheke Mandi',
  'Chak Seventy-eight North Branch',
  'Sohbatpur',
  'Sodhri',
  'Sobhodero',
  'Skardu',
  'Sīta Road',
  'Sinjhoro',
  'Sindh',
  'Sillanwali',
  'Sibi',
  'Sialkot',
  'Shujaabad',
  'Shorkot',
  'Shinpokh',
  'Shikarpur',
  'Shekhupura',
  'Sharqpur Sharif',
  'Shakargarh',
  'Shahr Sultan',
  'Shahpur Chakar',
  'Shahpur',
  'Shahdadpur',
  'Shahdad Kot',
  'Shabqadar',
  'Sehwan',
  'Sarikoran',
  'Sargodha',
  'Sarai Sidhu',
  'Sarai Naurang',
  'Sarai Alamgir',
  'Sann',
  'Sanjwal',
  'Sangla Hill',
  'Sanghar',
  'Samungli',
  'Sambrial',
  'Samaro',
  'Sakrand',
  'Saidu Sharif',
  'Sahiwal',
  'Sahiwal',
  'Saddiqabad',
  'Rustam',
  'Rojhan',
  'Rohri',
  'Rohbar',
  'Renala Khurd',
  'Rawalpindi',
  'Ratodero',
  'Rasulnagar',
  'Ranipur',
  'Rajo Khanani',
  'Rajanpur',
  'Raja Jang',
  'Raiwind',
  'Goth Radhan',
  'Quetta',
  'Qila Saifullah',
  'Qila Abdullah',
  'Kambar',
  'Qadirpur Ran',
  'Punjab Province',
  'Pithoro',
  'Pishin',
  'Pir Mahal',
  'Pindi Gheb',
  'Pindi Bhattian',
  'Pind Dadan Khan',
  'Pind',
  'Pirahin Tok',
  'Goth Phulji',
  'Phalia',
  'Peshawar',
  'Pattoki',
  'Pasrur',
  'Pasni',
  'Goth Nabi Bakhsh Panhwar',
  'Pano Aqil',
  'Panjgur',
  'Palandri',
  'Pakpattan',
  'Islamic Republic of Pakistan',
  'Paharpur',
  'Pad Idan',
  'Pabbi',
  'Ormara',
  'Okara',
  'Nushki',
  'Nowshera',
  'Khyber Pakhtunkhwa Province',
  'Gilgit-Baltistan',
  'New Mirpur',
  'Nawabshah',
  'Naushahro Firoz',
  'Naushahra Virkan',
  'Naushahra',
  'Naudero',
  'Goth Nathu Khan Khoso',
  'Nasirabad',
  'Narowal',
  'Narang Mandi',
  'Naukot',
  'Nankana Sahib',
  'Nagak Bazar',
  'Nabisar',
  'Muzaffargarh',
  'Muzaffarābād',
  'Mustafābād',
  'Musa Khel Bazar',
  'Murree',
  'Muridke',
  'Multan',
  'Moro',
  'Mohra Nur',
  'Model Town',
  'Mithi',
  'Mitha Tiwana',
  'Mirwah Gorchani',
  'Mirpur Sakro',
  'Mirpur Mathelo',
  'Mirpur Khas',
  'Mirpur Bhtoro',
  'Miro Khan',
  'Miran Shah',
  'Mingora',
  'Minchianabad',
  'Mianwali',
  'Mian Channun',
  'Mehrabpur',
  'Mehar',
  'Matli',
  'Matiari',
  'Mastung',
  'Mardan',
  'Mansehra',
  'Mankera',
  'Mangla',
  'Mandi Bahauddin',
  'Mananwala',
  'Mamu Kanjan',
  'Malakwal',
  'Malakand',
  'Mailsi',
  'Madeji',
  'Mach',
  'Loralai',
  'Lodhran',
  'Liliani',
  'Layyah',
  'Laro',
  'Larkana',
  'Langrial',
  'Landi Kotal',
  'Lalian',
  'Lala Musa',
  'Lakki',
  'Lakhi',
  'Lahore',
  'Ladhewala Waraich',
  'Lachi',
  'Kunri',
  'Kunjah',
  'Kundian',
  'Kulachi',
  'Kot Sultan',
  'Kot Samaba',
  'Kotri',
  'Kot Radha Kishan',
  'Kot Mumin',
  'Kot Malik Barkhurdar',
  'Kotli Loharan',
  'Kotli',
  'Kot Ghulam Muhammad',
  'Kot Diji',
  'Kot Addu',
  'Kohlu',
  'Kohat',
  'Khushāb',
  'Khurrianwala',
  'Khipro',
  'Khewra',
  'Kharian',
  'Kharan',
  'Karak',
  'Khapalu',
  'Khanpur',
  'Khanpur Mahar',
  'Khangarh',
  'Khangah Dogran',
  'Khanewal',
  'Khalabat',
  'Khairpur Nathan Shah',
  'Khairpur Tamewah',
  'Khairpur',
  'Khadro',
  'Keti Bandar',
  'Kasur',
  'Kashmor',
  'Karor',
  'Kario Ghanwar',
  'Karaundi',
  'Karachi Lines',
  'Karāchi District',
  'Karachi',
  'Kanganpur',
  'Kandiaro',
  'Kandiari',
  'Kandhkot',
  'Kamra',
  'Kamoke',
  'Chak One Hundred Twenty Nine Left',
  'Kamar Mushani',
  'Kamalia',
  'Kalur Kot',
  'Kallar Kahar',
  'Kaleke Mandi',
  'Kalat Lines',
  'Kalat',
  'Kalaswala',
  'Kalam',
  'Kalabagh',
  'Kahuta',
  'Kahror Pakka',
  'Kahna Nau',
  'Kadhan',
  'Kabirwala',
  'Johi',
  'Jiwani',
  'Chak Jhumra',
  'Jhol',
  'Jhelum',
  'Jhawarian',
  'Dera Allahyar',
  'Jhang Sadr',
  'Jauharabad',
  'Jatoi Shimali',
  'Jati',
  'Jaranwala',
  'Jandiala Sher Khan',
  'Jand',
  'Jamshoro',
  'Jampur',
  'Jam Gwang',
  'Jamak',
  'Jalalpur Pirwala',
  'Jalalpur Jattan',
  'Jahanian Shah',
  'Jacobabad',
  'Islamkot',
  'Islamabad',
  'Hyderabad',
  'Hujra Shah Muqim',
  'Hoshab',
  'Hirok',
  'Hingorja',
  'Hazro City',
  'Havelian',
  'Haveli Lakha',
  'Hasilpur',
  'Chak Thirty-one -Eleven Left',
  'Harunabad',
  'Harnoli',
  'Harnai',
  'Haripur',
  'Hangu',
  'Hala',
  'Haji Rahim Khan Jokhio',
  'Hafizabad',
  'Hadali',
  'Gwadar',
  'Gujrat',
  'Gujranwala',
  'Gujar Khan',
  'Goth Warayo',
  'Gorcop',
  'Gojra',
  'Gush Tang',
  'Gilgit',
  'Ghotki',
  'Ghauspur',
  'Gharo',
  'Garh Maharaja',
  'Garhiyasin',
  'Garhi Khairo',
  'Goth Garelo',
  'Garangwala',
  'Ganz',
  'Gandava',
  'Gambat',
  'Gakuch',
  'Gadani',
  'Fort Abbas',
  'Federally Administered Tribal Areas',
  'Fazilpur',
  'Chak Two Hundred Forty-nine Thal Development Authority',
  'Faruka',
  'Faqirwali',
  'Faisalabad',
  'Eminabad',
  'Dunyapur',
  'Dunga Bunga',
  'Dullewala',
  'Duki',
  'Dokri',
  'Doaba',
  'Upper Dir',
  'Diplo',
  'Dipalpur',
  'Dinga',
  'Dijkot',
  'Digri',
  'Dhoro Naro',
  'Dhok Mangtal',
  'Dhaunkal',
  'Dhanot',
  'Dera Ismail Khan',
  'Derai Baba',
  'Dera Ghazi Khan',
  'Dera Bugti',
  'Dehpalal',
  'Daur',
  'Daultala',
  'Daulatpur',
  'Daud Khel',
  'Daska Kalan',
  'Darya Khan Marri',
  'Darya Khan',
  'Daromehar',
  'Dalbandin',
  'Dajal',
  'Daira Din Panah',
  'Daggar',
  'Dadu',
  'Dadhar',
  'Chunian',
  'Chuchar-kana Mandi',
  'Chhor',
  'Choa Saidan Shah',
  'Chitral',
  'Chishtian',
  'Chiniot',
  'Chilas',
  'Chichawatni',
  'Cherat Cantonement',
  'Chawinda',
  'Isa Bazar',
  'Charsadda',
  'Chamber',
  'Chaman',
  'Chakwal',
  'Chak Azam Sahu',
  'Chak',
  'Chad',
  'Būrewāla',
  'Bulri',
  'Bozdar Wada',
  'Bhopalwala',
  'Bhit Shah',
  'Bhiria',
  'Bhimbar',
  'Bhera',
  'Bhawana',
  'Bhan',
  'Bhalwal',
  'Bhakkar',
  'Mianke Mor',
  'Bhag',
  'Berani',
  'Bela',
  'Begowala',
  'Bat Khela',
  'Battagram',
  'Basirpur',
  'Barkhan',
  'Bannu',
  'Bandhi',
  'Balochistan',
  'Bakhri Ahmad Khan',
  'Bahawalpur',
  'Bahawalnagar',
  'Bagh',
  'Bagarji',
  'Baffa',
  'Badin',
  'Baddomalhi',
  'Azad Kashmir',
  'Awaran',
  'Attock Khurd',
  'Attock City',
  'Ārya',
  'Arifwala',
  'Aman Garh',
  'Alizai',
  'Alipur',
  'Aliabad',
  'Akora',
  'Ahmadpur East',
  'Abbottabad',
  'Jhang City',
  'Badduki',
  'Bahawalnagar',
  'Tahsil',
  'Tāzān',
  'Nāmdārwāla',
  'Nigor',
  'Daud',
  'Tahsil',
  'Gaz Mar',
  'Passu',
  'Log Mulla Qadar Bakhsh',
  'Darbar Gharib Shah',
  'Dram Kol',
  'Mari Bazar',
  'Kārez',
  'Chibi',
  'Niami Kalag',
  'Kakhor',
  'Rekani',
  'Kochah',
  'Ziarat Shah Jawan',
  'Gondi',
  'Tahsil',
  'Ghati Dor',
  'Kiya Kalat',
  'Chibwari',
  'Akil Iomak',
  'Jammun',
  'Gulishah Kach',
  'Shakai',
  'Nowshera Cantonment',
  'Dhok Gangal',
  'Dal',
  'Surtagan Pass',
  'Surtagan Chib',
  'Hajiabad',
  'Alik Ghund',
  'Cantonment',
  'Khadan Khak',
  'Linju',
  'Shamshai',
  'Ahmadpur Sial',
  'Wahan Murad',
  'New Bādāh',
  'Goth Obhaio Mehar',
  'Tando Ghulam Ali',
  'Goth Vi Machhi',
  'Balach',
  'Dhunel Ganj',
  'Mianapura Khurd',
  'Chak Twenty-nine Bahawal Canal',
  'Chak Two Hundred Thirty-one Rakh Branch',
  'Chak Fourteen- Eight Right',
  'Saiyidan',
  'Kasi',
  'Ziarat Kharwari Baba',
  'Dera Murad Jamali',
  'Ziarat Shah-i-Mardan',
  'Relan',
  'Sadabad',
  'Jām Sāhib',
  'Chowki Jamali',
  'Bahawalpur Ghallu',
  'Setharja Old',
  'Babian',
  'Sawan',
  'Subedar Khan Khosa',
  'Sarai',
  'Risalpur Cantonment',
  'Noorabad',
  'Alpurai',
  'Malakwal City',
  'Mehmand Chak',
  'Basti Dosa',
  'Moza Shahwala',
  'Goth Chaudhary Attāullāh',
  'Allahabad',
  'Kashifabad',
  'Paoka',
  'Abdullahabad',
  'Sabzi Mandi',
  'Iqbal Camp',
  'Khuzdar',
  'Barkat Bhāi Town',
  'Dhok Halyan',
  'Haji Dur Muhammad',
  'Jinda Mirasi',
  'Sneuron',
  'Sonikot',
  'Eidgah',
  'Dasu',
  'Barishal',
  'Athmuqam',
  'Bindor',
  'Nazir Town',
  'Amirabad'
];
